# numpy

---

> python 效率代表


In [2]:
import numpy as np

## 数据结构

ndarry


In [ ]:
a = np.array([1, 1, 1, 1])
b = np.array([[1, 1], [1, 1]])
print(a,b)

b?

Type:        ndarray
String form:
[[1 1]
 [1 1]]
Length:      2
File:        c:\users\administrator.pc-202104131141.000\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of

生成数组的方法有很多

```python
import numpy.random
```

从**分布**中随机抽取


In [10]:
import numpy as np

a = np.random.random((4, 4))

b = np.random.normal((1, 1, 4))  # 正态分布

c = np.random.rand(4)
a, b, c

(array([[0.04340055, 0.23518814, 0.11763285, 0.78640522],
        [0.09358379, 0.99329944, 0.63739054, 0.00348929],
        [0.65711287, 0.79079108, 0.44320066, 0.87679285],
        [0.44324274, 0.38317774, 0.01907671, 0.14561872]]),
 array([ 0.29392213, -0.69359169,  4.43663021]),
 array([0.43343925, 0.9686345 , 0.25966091, 0.41936541]))

操作数组的方法有：

1. numpy 内建函数


In [ ]:
d = np.abs(b)
e = np.sin(b)
f = np.all(b)
g = b.mean()
h = b.T
i = b.std()
j = np.max()
print(d, e, f, g, h, i, sep="\n")
d, e, f, g, h, i

[0.29392213 0.69359169 4.43663021]
[ 0.28970837 -0.63930315 -0.96221888]
True
1.345653548452231
[ 0.29392213 -0.69359169  4.43663021]
2.22252085183687


(array([0.29392213, 0.69359169, 4.43663021]),
 array([ 0.28970837, -0.63930315, -0.96221888]),
 np.True_,
 np.float64(1.345653548452231),
 array([ 0.29392213, -0.69359169,  4.43663021]),
 np.float64(2.22252085183687))

2. 操作符


In [ ]:
c += 1
print(c)
c *= 2
print(c)
print(a @ a.T)  # 求法向量

[18.46751402 22.74907598 17.07728728 18.3549233 ]
[36.93502804 45.49815195 34.15457457 36.70984661]
[[0.68946773 0.3153959  0.95615319 0.22611521]
 [0.3153959  1.40168059 1.13253875 0.43475799]
 [0.95615319 1.13253875 2.0223404  0.73040631]
 [0.22611521 0.43475799 0.73040631 0.36485804]]


# pandas

---

> 可爱的熊猫


pandas 的数据主要是以`DataFrame`存储，是一个表。
||纬度（°N）|经度（°E）| 观测年份|AGPP（gC m-2 yr-1)|MAT（℃）|
|---|---|---|---|---|---|
|nih|18.73|108.89|2,006|1,919|20.84|
|66|18.73|108.89|2,007|1,919|20.61|


In [ ]:
import pandas as pd


a = pd.read_excel(r"..\data\中国陆地生态系统站点观测年总初级生产力数据集.xlsx")

Original columns: Index(['站点顺序号', '站点名称', '生态系统类型', '纬度（°N）', '经度（°E）', '观测年份',
       'AGPP（gC m-2 yr-1)', 'MAT（℃）', 'MAP（mm yr -1）', 'PAR（MJ m-2 yr-1）',
       'PET（mm yr -1）', 'VPD(kpa)', 'ρc,yr（mgCO2m-3）', 'SM（m3 m-3）',
       'SOC(gC m-2)', 'STN（gN m-2)', 'LAI（m2 m-2）', 'MLAI（m2 m-2）',
       '重复标志（1为重复）', '参考文献'],
      dtype='object')
