# numpy

---

> python 效率代表


In [2]:
import numpy as np

## 数据结构

ndarry


In [ ]:
a = np.array([1, 1, 1, 1])
b = np.array([[1, 1], [1, 1]])
print(a,b)

b?

Type:        ndarray
String form:
[[1 1]
 [1 1]]
Length:      2
File:        c:\users\administrator.pc-202104131141.000\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of

生成数组的方法有很多

```python
import numpy.random
```

从**分布**中随机抽取


In [10]:
import numpy as np

a = np.random.random((4, 4))

b = np.random.normal((1, 1, 4))  # 正态分布

c = np.random.rand(4)
a, b, c

(array([[0.04340055, 0.23518814, 0.11763285, 0.78640522],
        [0.09358379, 0.99329944, 0.63739054, 0.00348929],
        [0.65711287, 0.79079108, 0.44320066, 0.87679285],
        [0.44324274, 0.38317774, 0.01907671, 0.14561872]]),
 array([ 0.29392213, -0.69359169,  4.43663021]),
 array([0.43343925, 0.9686345 , 0.25966091, 0.41936541]))

操作数组的方法有：

1. numpy 内建函数


> 1. **矩阵点积**：
>
> - 如果你有两个向量 $ \mathbf{a} $ 和 $ \mathbf{b} $，它们的点积（内积）定义为：
>     $
>   \mathbf{a} \cdot \mathbf{b} = a_1 b_1 + a_2 b_2 + \dots + a_n b_n
>   $
> - 对于矩阵来说，点积通常指的是行向量与列向量的点积。例如，如果有矩阵 $ A $ 和矩阵 $ B $，那么它们的乘积 $
>   AB $ 是由行向量和列向量逐一点积组成的新矩阵。
>
> 2. **矩阵转置**：
>
> - 矩阵的转置是将其行与列互换。例如，矩阵 $ A $ 的转置为 $ A^T $，表示 $ A^T $ 中的第 $ i $ 行变成了原来的
>   第 $ i $ 列。
>   $
>   A = \begin{bmatrix}
>   a*{11} & a*{12} \\
>   a*{21} & a*{22}
>   \end{bmatrix}, \quad
>   A^T = \begin{bmatrix}
>   a*{11} & a*{21} \\
>   a*{12} & a*{22}
>   \end{bmatrix}
>   $


In [18]:
d = np.abs(b)
e = np.sin(b)
f = np.all(b)
g = b.mean()
h = b.T
i = b.std()
j = np.max()
print(d, e, f, g, h, i, sep="\n")
d, e, f, g, h, i

[0.29392213 0.69359169 4.43663021]
[ 0.28970837 -0.63930315 -0.96221888]
True
1.345653548452231
[ 0.29392213 -0.69359169  4.43663021]
2.22252085183687


(array([0.29392213, 0.69359169, 4.43663021]),
 array([ 0.28970837, -0.63930315, -0.96221888]),
 np.True_,
 np.float64(1.345653548452231),
 array([ 0.29392213, -0.69359169,  4.43663021]),
 np.float64(2.22252085183687))

2. 操作符


In [22]:
c += 1
print(c)
c *= 2
print(c)
print(a @ a.T)  # 求法向量

[18.46751402 22.74907598 17.07728728 18.3549233 ]
[36.93502804 45.49815195 34.15457457 36.70984661]
[[0.68946773 0.3153959  0.95615319 0.22611521]
 [0.3153959  1.40168059 1.13253875 0.43475799]
 [0.95615319 1.13253875 2.0223404  0.73040631]
 [0.22611521 0.43475799 0.73040631 0.36485804]]


[[nan nan]
 [nan nan]
 [nan nan]
 [nan nan]]


C:\Users\Administrator.PC-202104131141.000\AppData\Local\Temp\ipykernel_6292\813044945.py:8: RuntimeWarning: invalid value encountered in sqrt
  normalizedData = (data - data.mean()) / np.sqrt(data - data.mean() ** 2)


# pandas

---

> 可爱的熊猫


pandas 的数据主要是以`DataFrame`存储，是一个表。
||纬度（°N）|经度（°E）| 观测年份|AGPP（gC m-2 yr-1)|MAT（℃）|
|---|---|---|---|---|---|
|1|18.73|108.89|2,006|1,919|20.84|
|2|18.73|108.89|2,007|1,919|20.61|


In [1]:
import pandas as pd

a = pd.read_excel(r"..\data\中国陆地生态系统站点观测年总初级生产力数据集.xlsx")
a

站点顺序号     站点名称 生态系统类型    纬度（°N）     经度（°E）  观测年份  AGPP（gC m-2 yr-1)  \
0        1   尖峰岭森林'    森林'  18.72972  108.88972  2006        1919.000000   
1        1   尖峰岭森林'    森林'  18.72972  108.88972  2007        1919.000000   
2        1   尖峰岭森林'    森林'  18.72972  108.88972  2008        2138.000000   
3        1   尖峰岭森林'    森林'  18.72972  108.88972  2009        1904.000000   
4        2  儋州橡胶林2'    森林'  19.53790  109.46840  2013        2239.893154   
..     ...      ...    ...       ...        ...   ...                ...   
867    166    呼中森林'    森林'  51.11850  123.00260  2016         792.895920   
868    166    呼中森林'    森林'  51.11850  123.00260  2017         758.402841   
869    166    呼中森林'    森林'  51.11850  123.00260  2018         870.668074   
870    166    呼中森林'    森林'  51.11850  123.00260  2007         774.460000   
871    166    呼中森林'    森林'  51.11850  123.00260  2008         703.590000   

        MAT（℃）  MAP（mm yr -1）  PAR（MJ m-2 yr-1）  PET（mm yr -1）  VPD(kpa)  \
0    20.843288    1183.656683       2842.787468    1256.887448  0.525195   
1    20.609455    1080.848619       2723.291438    1250.564406  0.549332   
2    19.860581    1895.860437       2575.773190    1211.084410  0.504212   
3    20.943657    1994.032366       2670.678940    1262.928758  0.584169   
4    24.004523    2049.527788       2678.860352    1160.083154  0.670545   
..         ...            ...               ...            ...       ...   
867  -3.234723     483.377410       1904.806252     590.087144  0.263052   
868  -2.434834     434.281500       1861.261343     631.202411  0.296067   
869  -2.555139     526.450837       1862.407466     618.786720  0.274403   
870  -2.279710     364.284866       1934.857452     631.040073  0.317711   
871  -2.040991     452.705669       1858.450516     610.745235  0.285212   

     ρc,yr（mgCO2m-3）  SM（m3 m-3）  SOC(gC m-2)  STN（gN m-2)  LAI（m2 m-2）  \
0         715.037608    0.557954      1841.67      133.380     4.041304   
1         718.841368    0.595567      1841.67      133.380     4.865217   
2         724.523098    0.625159      1841.67      133.380     4.369565   
3         724.847007    0.574246      1841.67      133.380     4.065217   
4         772.801622    0.546073       326.25       50.625     3.202174   
..               ...         ...          ...          ...          ...   
867       787.285709    0.152884       971.73       82.350     2.684783   
868       789.373316    0.135668       971.73       82.350     1.993478   
869       794.328257    0.145561       971.73       82.350     2.436957   
870       745.487479    0.097082       971.73       82.350     2.141304   
871       748.987187    0.103069       971.73       82.350     2.106522   

     MLAI（m2 m-2）  重复标志（1为重复）  \
0             6.2           0   
1             6.2           0   
2             6.4           0   
3             5.9           0   
4             5.1           0   
..            ...         ...   
867           6.2           0   
868           5.7           0   
869           5.7           0   
870           4.9           0   
871           5.6           0   

                                                  参考文献  
0                   陈德祥.2010.尖峰岭热带山地雨林碳交换的动态特征和影响因素研究'  
1                   陈德祥.2010.尖峰岭热带山地雨林碳交换的动态特征和影响因素研究'  
2                   陈德祥.2010.尖峰岭热带山地雨林碳交换的动态特征和影响因素研究'  
3                   陈德祥.2010.尖峰岭热带山地雨林碳交换的动态特征和影响因素研究'  
4    ChinaFLUX，张晓娟, 2016. 海南岛西部橡胶林生态系统蒸散特征研究, 海南大学,...  
..                                                 ...  
867                                         ChinaFLUX'  
868                                         ChinaFLUX'  
869                                         ChinaFLUX'  
870  周丽艳, 贾丙瑞, 周广胜, 曾伟, 王宇 (2010) 中国北方针叶林生长季碳交换及其调控...  
871  周丽艳, 贾丙瑞, 周广胜, 曾伟, 王宇 (2010) 中国北方针叶林生长季碳交换及其调控...  

[872 rows x 20 columns]

行（列）主要是用`Series`存储


In [6]:
b = a.观测年份
b

0      2006
1      2007
2      2008
3      2009
4      2013
       ... 
867    2016
868    2017
869    2018
870    2007
871    2008
Name: 观测年份, Length: 872, dtype: int64

可以转换成`array`


In [ ]:
import numpy